apiVersion: v1
kind: Pod
metadata:
  name: basicserver3
  labels:
      component: webserver
spec:
  volumes:
  - name: myvol
    persistentVolumeClaim:
      claimName: test-pvc
  containers:
  - image: basicserver:0.43
    args:
    - /opt/venv/bin/python
    - /opt/app/basicserver3.py
    - Universe
    name: basicserver
    volumeMounts:
    - mountPath: "/data"
      name: myvol
    env:
    - name: GREETING
      value: Hi

